# export ZDOTDIR="$HOME/zsh"

eval "$(/opt/homebrew/bin/brew shellenv)"

export GPG_TTY=$(tty)

export PATH="/usr/local/bin:$PATH"
export PATH="$PATH:$HOME/Library/Python/3.6/bin"
export PATH="$PATH:$HOME/Library/Python/3.7/bin"
export PATH="$PATH:$(go env GOPATH)/bin"
export PATH="$PATH:$HOME/.fresh/source/freshshell/fresh/bin"
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
export PATH="$PATH:$HOME/.pyenv/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/.krew/bin"
export PATH="$(brew --prefix)/opt/ruby/bin:$PATH"
export PATH="$PATH:$(gem environment gemdir)/bin"
export PATH="$HOME/.rd/bin:$PATH"

export GOPATH=$(go env GOPATH)
export PIPENV_IGNORE_VIRTUALENVS=1
export PYENV_ROOT=$HOME/.pyenv

export AWS_PAGER=""

export KUBECTL_EXTERNAL_DIFF=kdiff

eval "$(direnv hook zsh)"
eval "$(rbenv init - zsh)"

source ~/.creds/secrets.env
