export ZDOTDIR="$HOME/zsh"

export PATH="/usr/local/bin:$PATH"
export PATH="$PATH:$(go env GOPATH)/bin"
export PATH="$PATH:$HOME/.fresh/source/freshshell/fresh/bin"

export GOPATH=$(go env GOPATH)

eval "$(direnv hook zsh)"
